LO-MEF01.pdf: ./Apunte-MEF012019.pdf ./MEF01_2018.pdf
	pdftk ./Apunte-MEF012019.pdf ./MEF01_2018.pdf cat output LO-MEF01.pdf


Apunte-MEF012019.pdf: ./Apunte-MEF012019.odt 
	libreoffice --convert-to pdf  ./Apunte-MEF012019.odt


./MEF01_2018.pdf: ./MEF01_2018.odp
	libreoffice --convert-to pdf  ./MEF01_2018.odp 
