001-Interpolacion.pdf: Clase_P02_Interpolacion2018.odp cuentas-interpolacion.odt
	libreoffice --convert-to pdf Clase_P02_Interpolacion2018.odp
	libreoffice --convert-to pdf cuentas-interpolacion.odt
	pdftk cuentas-interpolacion.pdf Clase_P02_Interpolacion2018.pdf cat output CuentasInterpolacion.pdf
