LO-MEF02.pdf: ./Apunte-MEF022020.pdf ./MEF02_2020.pdf 
	pdftk Apunte-MEF022020.pdf ./MEF02_2020.pdf cat output LO-MEF02.pdf

Apunte-MEF022020.pdf: ./Apunte-MEF022020.odt
	libreoffice --convert-to pdf ./Apunte-MEF022020.odt

MEF02_2020.pdf: ./MEF02_2020.odp
	libreoffice --convert-to pdf ./MEF02_2020.odp


