LO-MEF02.pdf: ./Apunte-MEF022019.pdf ./MEF02_2019.pdf
	pdftk ./Apunte-MEF022019.pdf ./MEF02_2019.pdf cat output LO-MEF02.pdf


./Apunte-MEF022019.pdf: ./Apunte-MEF022019.odt
	libreoffice --convert-to pdf ./Apunte-MEF022019.odt


./MEF02_2019.pdf: ./MEF02_2019.odp
	libreoffice --convert-to pdf ./MEF02_2019.odp
