all: Figure-MSHBlocks.pdf Figure-HeadNodes.pdf

Figure-MSHBlocks.pdf: Figure-MSHBlocks.tikz tikzsets.tikz
	pdflatex Figure-MSHBlocks.tikz

Figure-HeadNodes.pdf: Figure-HeadNodes.tikz tikzsets.tikz
	pdflatex Figure-HeadNodes.tikz
